// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msgpsbcojnaprrkkwgks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zZ3BzYmNvam5hcHJya2t3Z2tzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNDg3NzEsImV4cCI6MjA2NjYyNDc3MX0.SDGmGRy3yRg5NrdoN4VZgU1WoGW5VdDLY-Lst-X4W3Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);